### DISCUSSION TITLE
Making the insert mode indicator more visible and vibrant by default

### DISCUSSION THREAD

**Discussion by txtyash** [gdh1995/vimium-c#1032] [Q&A] [answered]
I'm aware that one can use css to change the look & feel of vimiumC but having an easily visible indicator would help a lot.
I usually avoid using insert mode for applications like youtube and use the trackpad instead just because the insert mode indicator mostly invisible to me.

Suggestions:
* Place it on top instead of bottom
* Use vibrant colors

**Comment by gdh1995** [comment, marked as answer]
You may write CSS rules to adjust the UI, like this:
![image](https://github.com/gdh1995/vimium-c/assets/5547703/2d47f71b-ac45-4007-a6f9-a471394ad800)

``` css
.HUD { top: 0; font-size: 24px; color: red; line-height: 28px; height: 30px }
.HUD::after{ border-radius: 0 0 8px 8px; }
```
