### DISCUSSION TITLE
How to make input box and notification box bigger?

### DISCUSSION THREAD

**Discussion by azzamsa** [gdh1995/vimium-c#1188] [Q&A]
Hi, 👋🏽 

How do we make the input box and notification box bigger?

![image](https://github.com/user-attachments/assets/a8bb5257-25ab-4472-8e52-707b1dc1ab50)

Thank you for vimium-c 🥞

**Comment by gdh1995** [comment]
You may write CSS code to change the UI appearance - see https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS

**Reply by gdh1995** [reply]
For example:
``` css
.HUD { height: 24px; font-size: 20px }
.HUD.UI { height: 26px; }
/* #find */
:host { height: 25px }
.r { height: 25px; }
.r > * { height: 20px; font-size: 20px }
```

![image](https://github.com/user-attachments/assets/f02748cc-8b78-4b0e-af93-fb27d6e8c49b)

**Reply by azzamsa** [reply]
![image](https://github.com/user-attachments/assets/a3f61b3d-702e-425b-ac8a-76d377f745b1)

I set the width to `9000px` but it still so small, how to make it as large as the green line?

```css
.HUD { height: 24px; width: 9000px; font-size: 24px }
.HUD.UI { height: 26px; width: 9000px }
```
