### DISCUSSION TITLE
Highlight scrollable area

### DISCUSSION THREAD

**Discussion by Fred-Vatin** [gdh1995/vimium-c#1284] [Show and tell]
In Vimium settings `Custom CSS for Vimium C UI`, set this:
```css
/* #ui */
/* background for hint on scrollable elements */
.BH {
	color: #fff;
	background: #5c008a !important;
	border: 2px solid #ff03d8 !important;
}
```

Then when using such a command:
```
map f LinkHints.activateHover
```

hints for scrollable area will be highlighted like this
![image](https://github.com/user-attachments/assets/3e97e661-bc7b-4cf0-96ec-36ec6e4fded1)

To get the focus back on the main frame, use something like this:
```
map W mainFrame
```
The scroll should switch to the main frame. If you use `LinkHints.activateFocus` instead of `LinkHints.activateHover` the focus will still be active on element and pressing `tab` will use this element as a starting point. But the scroll action is set to main frame.

See more here #1285
