### ISSUE TITLE
Custom CSS stopped working today in Chromium extension.

### ISSUE THREAD

**Issue by theherk** [gdh1995/vimium-c#1100]
**Describe the bug**

Starting today, my custom css no longer has any effect. It still works in the Firefox addon, but no in the Chromium extension.

**To Reproduce**

<details>
  <summary>custom css (expand)</summary>

  ```css
  /* #ui */

  .D>.LH {
      background: #1a1b26;
      color: #2ac3de;
      border-color: #bb9af7;
      scale: 1.33;
  }

  /* #omni */

  #bar {
      background: #1a1b26;
      border-color: #bb9af7;
  }

  #input {
      background: #24283b;
      border-color: #bb9af7;
  }

  .item {
      background: #1a1b26;
  }

  .top {
      color: #9aa5ce;
  }

  .bottom {
      color: #a9b1d6;
  }

  .history {
      fill: #e0af68;
  }
  ```

</details>

**Browser, OS and Vimium C versions**

- Browser name: Arc
- Browser version: Version 1.31.2 (46819) / Chromium Engine Version 122.0.6261.57 (arm64)
- Vimium C version: 1.99.99
- OS name and version: macOS Sonoma 14.3.1 (23D60)

The Firefox version that still works is `Vimium C 1.99.997, Firefox 122, macOS`.
