### ISSUE TITLE
V 2.11  Chrome 下自定义主题不生效

### ISSUE THREAD

**Issue by lonelygo** [gdh1995/vimium-c#1170]
接受权限警告后，重启浏览器，发现自定义的主题不生效了。
删除自定义 css 文件，重新复制进去还是不生效。
删除自定义主题，参考 [Wiki](https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-custom-CSS) 中de   using custom CSS 的例子尝试验证问题在自己的 CSS 还是插件，发现无论如何修改都不生效。

**Comment by Shu-Ji** [comment]
我的现象是，升级后，Chrome权限警告后，直接就无法启用插件了

**Comment by ascodeasice** [comment]
我自己是只有 omnibar 的主題不對，測試以後發現需要把把 /* #omni / 改成 /* #omnibar */

**Comment by gdh1995** [comment]
没动什么叫做删除自定义 css 文件。
要不截图看看 自定义 css 里填的内容？

**Comment by ZeusVS** [comment]
I have the same issue, only the /* omnibar */ custom css isn't working/applying, the rest is behaving as expected.

**Comment by gdh1995** [comment]
Sorry it's indeed a bug of Vomnibar, and there's no way to work it around in v2.11 .

I'll fix it in days.

**Comment by lonelygo** [comment]
> 没动什么叫做删除自定义 css 文件。 要不截图看看 自定义 css 里填的内容？

我用的 Dracula vimium css，在这里[Dracula Theme for Vimium](https://draculatheme.com/vimium)

```css
/*
Dracula theme for Vimium
by Trollwut (trollwut@trollwut.org). This code is in the public domain.
To use:
  1. Copy the code.
  2. Go to the Vimium options.
  3. Click Show Advanced Options.
  4. Under Advanced Options, scroll down to CSS for link hints.
  5. Paste the code in the text field.
  6. Click Save Changes.
  7. Go to the website of your choice (or, if you have it open already, reload it) and check out the results.
*/

/* Link hint boxes */
div > .vimiumHintMarker {
  background: #282a36;
  font-size: 12px;
  border: 0.25em solid #ffb86c;
  border-radius: 0.34em;
  box-shadow: 0em 0.1em 0.6em 0.1em rgba(0, 0, 0, 0.4);
}

/* Link hint text */
div > .vimiumHintMarker span {
  color: #f8f8f2;
  font-size: inherit;
  text-shadow: none;
}

/* Link hint matching characters */
div > .vimiumHintMarker > .matchingCharacter {
  color: #6272a4;
}

/* HUD ("heads-up display") bar */
div.vimiumHUD {
  background: #282a36;
  border: 1px solid #6272a4;
}

div.vimiumHUD .vimiumHUDSearchArea {
  background: #282a36;
}

div.vimiumHUD .hud-find {
  background: #282a36;
  border: none;
  color: #f8f8f2;
}

div.vimiumHUD span#hud-find-input{
  color: #f8f8f2;  /* 'Foreground' color */
}

div.vimiumHUD span#hud-match-count {
  color: #6272a4;  /* 'Comment' color */
}

div.vimiumHUD .vimiumHUDSearchAreaInner {
  color: #6272a4;  /* 'Comment' color */
}

#vomnibar{
    background-color: #44475A;
}

#vomnibar input {
  color: #f8f8f2;
  font: -moz-window;
  /*font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;*/
  font-size: 20px;
  height: 34px;
  margin-bottom: 0;
  padding: 4px;
  background-color: #282a36;
  border-radius: 3px;
  border: 1px solid #6272a4;
  box-shadow: #bd93f9 0px 0px 1px;
  width: 100%;
  outline: none;
  box-sizing: border-box;
}

#vomnibar .vomnibarSearchArea {
  display: block;
  padding: 10px;
  background-color: #6272a4;
  border-radius: 4px 4px 0 0;
  border-bottom: 0px solid #bd93f9;
}

#vomnibar ul {
  background-color: #44475a;
  border-radius: 0 0 4px 4px;
  list-style: none;
  padding-top: 0;
  padding-bottom: 0;
  margin-block-start: 2px;
  margin-block-end: 0px;
}

#vomnibar li {
  border-bottom: 1px solid #6272a4;
  line-height: 1.1em;
  padding: 7px 10px;
  font-size: 16px;
  color: #f8f8f2;
  position: relative;
  display: list-item;
  margin: auto;
}

#vomnibar li .vomnibarBottomHalf {
  font-size: 15px;
  margin-top: 3px;
  padding: 2px 0;
}

#vomnibar li .vomnibarSource {
  color: #bd93f9;
  margin-right: 4px;
}
#vomnibar li .vomnibarRelevancy {
  position: absolute;
  right: 0;
  top: 0;
  padding: 5px;
  background-color: #282a36;
  color: #f8f8f2;
  font-family: monospace;
  width: 100px;
  overflow: hidden;
}

#vomnibar li .vomnibarUrl {
  white-space: nowrap;
  color: #50fa7b;
}

#vomnibar li .vomnibarMatch {
  font-weight: bold;
  color: #ffb86c;
}

#vomnibar li em, #vomnibar li .vomnibarTitle {
  color: #f8f8f2;
  margin-left: 4px;
  font-weight: normal;
}
#vomnibar li em { font-style: italic; }
#vomnibar li em .vomnibarMatch, #vomnibar li .vomnibarTitle .vomnibarMatch {
  color: #ffb86c;
}

#vomnibar li.vomnibarSelected {
  background-color: #6272a4;
  font-weight: normal;
}

#vomnibarInput::selection {
  background-color: #8be9fd;
}
```
