### ISSUE TITLE
hint charachter is not visible if you active Force Dark Mode for Web Contents

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#152]
hi
I active `Force Dark Mode for Web Contents` in `chrome://flags` so hint character color reverse.
it hard to read them. 
is it possible to exclude them or a way to change hint color(i like default yellow color)?
i can't find a good documentation for change vimium-c theme.

**Comment by gdh1995** [comment]
You may configure the "Custom CSS for Vimium UI" in advanced options on Vimium C Options page.

This issue is the same as #111, and can not be solved by extensions.

Here's a sample from another user (https://github.com/gdh1995/vimium-c/issues/111#issuecomment-583569154):
``` CSS
.D > .LH { background: green; }
.LH { border: 0.5px solid lightgreen; }
```

**Comment by Monirzadeh** [comment]
thank you

**Comment by Monirzadeh** [comment]
> You may configure the "Custom CSS for Vimium UI" in advanced options on Vimium C Options page.
> 
> This issue is the same as #111, and can not be solved by extensions.
> 
> Here's a sample from another user ([#111 (comment)](https://github.com/gdh1995/vimium-c/issues/111#issuecomment-583569154)):
> 
> ```css
> .D > .LH { background: green; }
> .LH { border: 0.5px solid lightgreen; }
> ```

@gdh1995 this code not working on version 1.83.4 anymore
any thing change?

**Comment by gdh1995** [comment]
@Monirzadeh  Yes there's a new regression. For v1.83.4, please write:
``` css
}
.LH { background: green; }
.LH { border: 0.5px solid lightgreen; }
```

Note a prefix of `}` and no `.D >`.
