### ISSUE TITLE
change background color of `/` results 

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#271]
I want to change the background color of the find in page `/` results (not ctrl+f)
I tried
```CSS
/* #find */ 
::selection { background: green !important; }
```
as from https://github.com/gdh1995/vimium-c/blob/master/front/vimium-c.css
but without success
I also tried putting the selector in other sections.
