### ISSUE TITLE
Hints are displayed erroneously when user injected CSS is present

### ISSUE THREAD

**Issue by NightMachinary** [gdh1995/vimium-c#445]
**Describe the bug**

**To Reproduce**

- Normal behavior
![image](https://user-images.githubusercontent.com/36224762/134797767-df342cf3-f548-4d78-aa73-e7dbbb2cd3d4.png)

- After injecting custom CSS (with [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en))
![image](https://user-images.githubusercontent.com/36224762/134797745-0c03e00b-8c0f-44b0-bbb7-668647cc6929.png)

```css
#left-sidebar,
.s-sidebarwidget,
#hot-network-questions {
    display: none;
}

#content {
    margin-left: 0px;
    margin-right: 0px;
    zoom: 1.37;
}

.inbox-dialog {
    /* inbox items */
    zoom: 1.5;
    /* width: 130% !important; */
}

.s-prose {
    font-size: 1.4em !important;
}

.comment-body {
    font-size: 1.3em !important;
}


#answers {
    /* width: 70vw; */
}

.container {
    width: max-content !important;
    max-width: 99999px !important;
}
```

**Browser, OS and Vimium C versions**

- Browser name: Chrome 93.0.4577.63 (Official Build) (x86_64)
- Vimium C version: 1.92.4
- OS name and version: macOS 11

**Comment by gdh1995** [comment]
`zoom` property is a bad thing and there's no easy way to work around its impact. Please consider about using `transform: scale(...)`.

**Comment by gdh1995** [comment]
In other words, please avoid zooming in a large area, and you should use font-size or only zoom some small areas.

**Comment by NightMachinary** [comment]
Yes, using `transform: matrix(1.37, 0, 0, 1.37, 80, 400);` instead of `zoom: 1.37;` works, though it needs hardcoding the translation transform.

**Comment by gdh1995** [comment]
See https://stackoverflow.com/questions/23760845/css-scale-from-left-top and `transform-origin` can solve your question.

**Comment by NightMachinery** [comment]
@gdh1995 Is it possible to fix the issue with `zoom`? I tried using transforms, but they don't quite work.

Here is my userstyle for StackExchange sites:
Using
```css
    transform: matrix(1.37, 0, 0, 1.37, -90, 0); 
    transform-origin: left top;
```
instead of `zoom` makes the dialogues that open (e.g., when asking a new question) to open in the wrong place. `transform-origin` cannot properly center the content without the explicit `-90` translation.

```css
#left-sidebar,
.s-sidebarwidget,
#hot-network-questions {
    display: none;
}

#content {
    margin-left: 0px;
    margin-right: 0px;
   
    zoom: 1.37;

    /*
    transform: matrix(1.37, 0, 0, 1.37, -90, 0); 
    transform-origin: left top;
    */
}

.inbox-dialog {
    /* inbox items */
    zoom: 1.5;
    /* width: 130% !important; */
}

.s-prose {
    font-size: 1.4em !important;
}

.comment-body {
    font-size: 1.3em !important;
}


#answers {
    /* width: 70vw; */
}

.container {
    width: max-content !important;
    max-width: 99999px !important;
}

pre, code {
  /* enables text wrapping */
  white-space: pre-wrap; /* Since CSS 2.1 */
  white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
  white-space: -pre-wrap; /* Opera 4-6 */
  white-space: -o-pre-wrap; /* Opera 7 */
  word-wrap: break-word; /* Internet Explorer 5.5+ */
  /* */
}
```
