### ISSUE TITLE
How to do i remove animations and icons in vomnibar?

### ISSUE THREAD

**Issue by nikinbaidar** [gdh1995/vimium-c#759]
**Browser and OS**
- Browser name: Firefox 104.0
- OS name: Arch Linux

I've been using Vimium for a while now and just recently started using vimium-c, there a few issues that I can't seem to resolve:

1) When I press o to trigger vomnibar and start typing it displays some icons on the left, how do I disable them?
2) When I press "gi" to focus a search bar there is box that appears for a second, how do I turn this animation off?

Thank you.

**Comment by gdh1995** [comment]
1. add this to `Custom CSS for Vimium C UI` on Vimium C Options page (https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-custom-CSS):
``` css
/* #omni */
.icon { background: none !important; padding-right: 0px; }
```

2. You may add the below code, but it will also disable flash boxes of other modes like `LinkHints`
``` css
.Flash { display: none !important; }
```
